name: 'PR Labels'
description: 'Automatically label PRs based on the branch prefix'
inputs:
  token:
    description: 'GitHub Token for the user to perform label additions. Use `secrets.GITHUB_TOKEN` for the actions bot'
    required: true
outputs:
  result:
    description: The label applied to the Pull Request. If no label was applied this will be null.
runs:
  using: 'node12'
  main: 'index.js'
